build:
  environment:
    php:
      version: 7.4
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

checks:
  php: true

tools:
  external_code_coverage:
    timeout: 600
    runs: 3
