build:
  environment:
    php:
      version: 7.4
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
    coverage:
      tests:
        override:
          - command: vendor/bin/phpunit --coverage-clover=clover.xml
            coverage:
              file: clover.xml
              format: clover

checks:
  php: true

tools:
  external_code_coverage:
    timeout: 600
    runs: 3
