dist: trusty
language: php

php:
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist --ignore-platform-reqs

script:
  - vendor/bin/phpunit --coverage-clover=coverage-clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage-clover.xml
